apiVersion: v2
publisher: radon
name: radon-ctt-ide-plugin
version: 0.0.1
type: VS Code extension
displayName: radon-ctt-ide-plugin
title: Radon CTT IDE Plugin
description: Execution of the continuous testing tool from the IDE.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/radon-h2020/radon-ctt-ide-plugin
category: Other
spec:
  extensions:
    - https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-ctt/0.0.1/radon-ctt-ide-plugin.vsix
