apiVersion: v2
publisher: radon
name: radon-dec-plugin
version: 0.0.3
type: VS Code extension
displayName: RADON Decomposition
title: RADON Decomposition Plugin
description: A plugin for invoking the RADON decomposition tool
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/radon-h2020/radon-decomposition-plugin
category: Other
spec:
  extensions:
    - https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-decomposition/0.0.3/radon-dec-plugin.vsix
