apiVersion: v2
publisher: radon
name: radon-vt-plugin
version: 0.0.5
type: VS Code extension
displayName: RADON-h2020 VT plugin
title: RADON VT plugin
description: The che plugin for RADON VT
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/radon-h2020/radon-plugin-registry
category: Other
spec:
  extensions:
    - https://raw.githubusercontent.com/radon-h2020/radon-plugin-registry/master/radon/radon-vt/0.0.5/radon-vt-plugin.vsix
